services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: r00tpw
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: r00tpw
    depends_on:
      - mysql

  wp:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: r00tpw
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    deploy:
      replicas: 3
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wp

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://nginx --users 5 --spawn-rate 1

volumes:
  mysql:
  wordpress:
